; PlatformIO Project Configuration File

; ── USB flash (use this now, one last time) ──────────────────
[env:esp32_usb]
platform      = espressif32
board         = esp32doit-devkit-v1
framework     = arduino
monitor_speed = 115200
upload_port   = COM9
monitor_port  = COM9

lib_deps =
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    emelianov/modbus-esp8266
    bblanchon/ArduinoJson

; ── OTA flash (use this forever after) ──────────────────────
[env:esp32_ota]
platform      = espressif32
board         = esp32doit-devkit-v1
framework     = arduino
monitor_speed = 115200
monitor_port  = COM9

upload_protocol = espota
upload_port     = 10.10.10.206
upload_flags    =
    --auth=flash1234

lib_deps =
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    emelianov/modbus-esp8266
    bblanchon/ArduinoJson