; =========================
; 🔹 1. INITIAL SETUP (USB)
; =========================
[env:initial_setup]
platform      = espressif32
board         = esp32doit-devkit-v1
framework     = arduino

upload_port   = COM9
monitor_port  = COM9
monitor_speed = 115200

lib_deps =
    tzapu/WiFiManager


; =========================
; 🔹 2. OTA UPLOAD (WiFi)
; =========================
[env:esp32_ota]
platform      = espressif32
board         = esp32doit-devkit-v1
framework     = arduino

upload_protocol = espota
upload_port     = 10.10.10.227   ; 🔥 PUT YOUR ESP IP HERE
upload_flags =
    --auth=flash1234

monitor_speed = 115200
; ❌ remove this (not needed)
; monitor_port  = socket://ESP32-CNC02.local:23

lib_deps =
    tzapu/WiFiManager